### ISSUE TITLE
Please add support for Chipped

### ISSUE THREAD

**Issue by purejosh** [Exceptionflug/protocolize-data#1]
Please ping me on discord for anything you need.  purejosh#2047

```
[23:29:36 WARN] [dev.simplix.protocolize.data.packets.OpenWindow]: Unknown inventory type 28 in protocol version 758
[23:29:36 ERROR] [Protocolize]: === EXCEPTION CAUGHT IN DECODER ===
[23:29:36 ERROR] [Protocolize]: Protocolize 2.2.1:331
[23:29:36 ERROR] [Protocolize]: Stream Direction: UPSTREAM
[23:29:36 ERROR] [Protocolize]: InboundConnection: [connected player] purejosh (/192.34.113.4:2049), ServerConnection: null
[23:29:36 ERROR] [Protocolize]: Protocol version: 1.18.2
[23:29:36 ERROR]: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "dev.simplix.protocolize.data.inventory.InventoryType.getTypeId(int)" because "this.inventoryType" is null
[23:29:36 ERROR]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[23:29:36 ERROR]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[23:29:36 ERROR]: 	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[23:29:36 ERROR]: 	at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:230)
[23:29:36 ERROR]: 	at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handleGeneric(BackendPlaySessionHandler.java:276)
[23:29:36 ERROR]: 	at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:143)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[23:29:36 ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[23:29:36 ERROR]: 	at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[23:29:36 ERROR]: 	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:89)
[23:29:36 ERROR]: 	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[23:29:36 ERROR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[23:29:36 ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[23:29:36 ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[23:29:36 ERROR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[23:29:36 ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[23:29:36 ERROR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[23:29:36 ERROR]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[23:29:36 ERROR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
[23:29:36 ERROR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
[23:29:36 ERROR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
[23:29:36 ERROR]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
[23:29:36 ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[23:29:36 ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[23:29:36 ERROR]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[23:29:36 ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23:29:36 ERROR]: Caused by: java.lang.NullPointerException: Cannot invoke "dev.simplix.protocolize.data.inventory.InventoryType.getTypeId(int)" because "this.inventoryType" is null
[23:29:36 ERROR]: 	at dev.simplix.protocolize.data.packets.OpenWindow.write(OpenWindow.java:87)
[23:29:36 ERROR]: 	at dev.simplix.protocolize.velocity.packet.VelocityProtocolizePacket.encode(VelocityProtocolizePacket.java:66)
[23:29:36 ERROR]: 	at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:51)
[23:29:36 ERROR]: 	at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:29)
[23:29:36 ERROR]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[23:29:36 ERROR]: 	... 52 more
```

**Comment by Exceptionflug** [comment]
Hello,

we won't add support for minecraft mods, I'm sorry.

**Comment by purejosh** [comment]
People use and love Velocity. Having a modded fabric server behind a Velocity client really shouldn't be so unreasonable. Why would you not want to add support for modding? 

Every choice revolutionizes the future of minecraft, and a proxy network with a modded fabric server provides variety for all. I urge you to reconsider.

**Comment by purejosh** [comment]
Just to let you know, removing Protocolize resolved the issues I was having with Chipped, and it now works as intended. I'm not sure why your plugin was interfering with packets that are unrelated to its use case? But it is what it is. 

Hopefully there's another alternative for plugins that utilize Protocolize, as this one is clearly performing outside of its intended scope.
