### ISSUE TITLE
Interacting with an item with custom enchants causes a internal server error message

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Exceptionflug/protocolize-data#12]
Getting the below error message when interacting with an item enchanted with an enchant from ExcellentEnchants,

Using latest velocity and protocolize versions;

Purpur Server Error Message:
``SirOMGitsYOU lost connection: Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'serverbound/minecraft:container_click'``

Velocity Error Message:
`[23:46:33 ERROR] [Protocolize]: Unable to write item on protocol version 767
java.lang.RuntimeException: Unable to write EnchantmentsComponentImpl of item
        at dev.simplix.protocolize.api.item.StructuredItemStackSerializer.writeComponent(StructuredItemStackSerializer.java:96) ~[?:?]
        at dev.simplix.protocolize.api.item.StructuredItemStackSerializer.write(StructuredItemStackSerializer.java:73) ~[?:?]
        at dev.simplix.protocolize.api.item.ItemStackSerializer.write(ItemStackSerializer.java:201) ~[?:?]
        at dev.simplix.protocolize.data.packets.ClickWindow.write(ClickWindow.java:118) ~[?:?]
        at dev.simplix.protocolize.velocity.packet.VelocityProtocolizePacket.encode(VelocityProtocolizePacket.java:78) ~[?:?]
        at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:54) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:32) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:956) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:982) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:950) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.write(MinecraftConnection.java:234) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler.handleGeneric(ClientPlaySessionHandler.java:460) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:154) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:91) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:60) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-431.jar:3.3.0-SNAPSHOT (git-0cd069ec-b431)]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "dev.simplix.protocolize.data.Enchantment.name()" because the return value of "java.util.Map$Entry.getKey()" is null
        at dev.simplix.protocolize.data.item.component.EnchantmentsComponentImpl.write(EnchantmentsComponentImpl.java:53) ~[?:?]
        at dev.simplix.protocolize.api.item.StructuredItemStackSerializer.writeComponent(StructuredItemStackSerializer.java:94) ~[?:?]
        ... 61 more`

**Comment by Exceptionflug** [comment]
Hey, what are the involved client and server versions?

**Comment by SirOMGitsYOU** [comment]
> Hey, what are the involved client and server versions?

1.21.1 client & server and velocity version 436

**Comment by ZuRiKanHD** [comment]
Is there already a solution to this problem? We have the same problem!

**Comment by JunTVDE** [comment]
+1
I really want to use Protocolize but that issue keeps us from updating to minecraft 1.21... :(
